default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres  # PostgreSQLのユーザー名（デフォルトは "postgres"）
  password: password  # ここにPostgreSQLのパスワードを設定
  host: localhost     # ローカルでPostgreSQLを使う場合
  port: 5432          # PostgreSQLのデフォルトポート

development:
  <<: *default
  database: backend_development

test:
  <<: *default
  database: backend_test

production:
  primary: &primary_production
    <<: *default
    database: backend_production
    username: backend
    password: <%= ENV["BACKEND_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: backend_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: backend_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: backend_production_cable
    migrations_paths: db/cable_migrate
