services:
  backend:  # ✅ `web` を `backend` に変更
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: >
      sh -c "rm -f tmp/pids/server.pid &&
             bundle exec rails s -b 0.0.0.0"
    volumes:
      - ./backend:/app
    ports:
      - "4000:3000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@db:5432/chatting_backend
      REDIS_URL: redis://redis:6379/0
    networks:
      - app-network

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: chatting_backend
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d chatting_backend"]
      interval: 10s
      retries: 5
    networks:
      - app-network

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5
    networks:
      - app-network

  sidekiq:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: bundle exec sidekiq
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@db:5432/chatting_backend
      REDIS_URL: redis://redis:6379/0
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro  # ✅ nginx.conf を追加
    ports:
      - "8080:80"
    depends_on:
      - backend  # ✅ `web` → `backend`
    networks:
      - app-network

  swagger:
    image: swaggerapi/swagger-ui
    volumes:
      - ./swagger:/usr/share/nginx/html/swagger  # ✅ `swagger` ディレクトリをマウント
    environment:
      SWAGGER_JSON: /swagger/swagger.json  # ✅ 修正: `swagger.json` の場所を正しく指定
    ports:
      - "8081:8080"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro  # ✅ ルート nginx.conf を使用
      - ./nginx/ssl:/etc/nginx/ssl:ro  # ✅ SSL 証明書
    depends_on:
      backend:  # ✅ `web` → `backend`
        condition: service_started
      frontend:
        condition: service_started
      swagger:
        condition: service_started
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
