services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: chattting_backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - bundle_cache:/gems
      - ./backend/docker/entrypoint.sh:/app/entrypoint.sh
    entrypoint: ["/app/entrypoint.sh"]

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: chattting_web
    restart: always
    ports:
      - "5173:5173"  # React のデフォルトポート
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://localhost:3000  # API のベースURLを設定
    volumes:
      - ./frontend:/app
      - /app/node_modules  # コンテナの node_modules をホストと分離
    command: ["npm", "run", "dev"]  # React 開発サーバーを起動

  postgres:
    image: postgres:14
    container_name: chattting_postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      retries: 5
      start_period: 20s

  redis:
    image: redis:6.2
    container_name: chattting_redis
    restart: always
    ports:
      - "6379:6379"
    env_file:
      - ./backend/.env
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      start_period: 20s

volumes:
  postgres_data:
  redis_data:
  bundle_cache:
